### ISSUE TITLE
isisdl-config crashes when cron is not installed

### ISSUE THREAD

**Issue by tsprinz** [Emily3403/isisdl#1]
**Issue:** `isisdl-config` attempts to access /usr/bin/crontab and crashes if it doesn't exist.

**Proposed solution:**

- `isisdl-config` should access `crontab` only if (and after) the user requested a cron-job to be created/deleted.
- `isisdl-config` should show an error message if `crontab` doesn't exist, prompting the user to install it before rerunning `isidl-config` and the exit gracefully. (only if user requested a cron-job to be created)
- Bonus: For maximum user comfort, include a systemd-timer-option for systems without cron.

**OS:** Archlinux (Linux Kernel Ver. 5.15.12-arch1-1)

**Traceback:**
```
Traceback (most recent call last):
  File "/home/<user>/.local/bin/isisdl-config", line 8, in <module>
    sys.exit(main())
  File "/home/<user>/.local/lib/python3.10/site-packages/isisdl/bin/config.py", line 248, in main
    cron_prompt()
  File "/home/<user>/.local/lib/python3.10/site-packages/isisdl/bin/config.py", line 160, in cron_prompt
    with CronTab(user=True) as cron:
  File "/home/<user>/.local/lib/python3.10/site-packages/crontab.py", line 228, in __init__
    self.read(tabfile)
  File "/home/<user>/.local/lib/python3.10/site-packages/crontab.py", line 291, in read
    (out, err) = open_pipe(self.cron_command, l='', **self.user_opt).communicate()
  File "/home/<user>/.local/lib/python3.10/site-packages/crontab.py", line 190, in open_pipe
    return sp.Popen(args, stdout=sp.PIPE, stderr=sp.PIPE, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/crontab'
Exception ignored in atexit callback: <function OnKill.exit at 0x7fb23afc2830>
Traceback (most recent call last):
  File "/home/<user>/.local/lib/python3.10/site-packages/isisdl/backend/utils.py", line 235, in exit
    import isisdl.backend.request_helper as request_helper
  File "/home/<user>/.local/lib/python3.10/site-packages/isisdl/backend/request_helper.py", line 9, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/lib/python3.10/concurrent/futures/__init__.py", line 49, in __getattr__
    from .thread import ThreadPoolExecutor as te
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 37, in <module>
    threading._register_atexit(_python_exit)
  File "/usr/lib/python3.10/threading.py", line 1497, in _register_atexit
    raise RuntimeError("can't register atexit after shutdown")
RuntimeError: can't register atexit after shutdown
```

**Comment by Emily3403** [comment]
Thanks for the bug report. It seems as if it is a bug in a package that isisdl depends on. If the creation of CronJob fails, it will only displays the Option [No] when prompting for the cron-job

**Comment by Emily3403** [comment]
I'm currently looking into systemd-timers as they provide a greater feature set and are superior to Cron. Do you have any recommendation on how a config file should look like or a pitfall that might arise?

Cheers!
